import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const geistHeading = Geist({ subsets: ['latin'], variable: '--font-heading' });

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Sayzo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-sans", inter.variable, geistHeading.variable)}>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Provider>
          {children}
          <Toaster richColors position="bottom-left" />
        </Provider>
      </body>
    </html>
  );
}
